name: Build ObjectDetection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable with PyInstaller
        run: pyinstaller --noconsole --onefile --name ObjectDetection main.py

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build installer with Inno Setup
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer_script.iss

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: ObjectDetectionInstaller
          path: ObjectDetectionInstaller.exe
